import { ThemeToggleButton } from "@/components/global";
import { Providers } from "@/providers/provider";
import type { Metadata } from "next";
import "./globals.css";


/**
 * Metadados estáticos para a aplicação Next.js.
 *
 * Estes metadados são usados para SEO e para configurar a aparência da página
 * em navegadores e mídias sociais (ex: título na aba do navegador).
 *
 * @type {Metadata}
 */
export const metadata: Metadata = {
  title: "Template Next App",
  description: "Generated by template next app",
};

/**
 * Layout raiz principal de toda a aplicação Next.js.
 *
 * Este componente define a estrutura HTML básica (`<html>`) e aninha
 * o componente `Providers` para fornecer contexto e estados globais
 * (autenticação, tema, queries, etc.) a toda a aplicação.
 *
 * @param {Object} props - As propriedades do componente.
 * @param {React.ReactNode} props.children - O conteúdo da página ou layout aninhado
 * a ser renderizado dentro do `Providers` e da tag `<html>`.
 * @returns {JSX.Element} A estrutura HTML raiz da aplicação.
 */
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR" suppressHydrationWarning>
      <Providers>
        {children}
        <ThemeToggleButton />
      </Providers>
    </html>
  );
}